const hehe= {
  "data": {
      "result": true,
      "listDexuat": [
          {
              "_id": "654a129b962b51d7806d10ba",
              "creator": {
                  "_id": 17496,
                  "email": "tuananhhust05@gmail.com",
                  "phoneTK": "",
                  "userName": "Nguyễn Tuấn Anh",
                  "alias": "adfultre",
                  "phone": "0339170155",
                  "emailContact": null,
                  "avatarUser": "app1691748972_360 3.jpg",
                  "type": 2,
                  "city": 1,
                  "district": 82,
                  "address": "Đức Lý, Lý Nhân, Hà Nam",
                  "otp": "0",
                  "authentic": 1,
                  "isOnline": 1,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1681531709,
                  "updatedAt": 1699424378,
                  "lastActivedAt": "2023-11-08T06:19:38.415Z",
                  "time_login": 1690970480,
                  "role": 0,
                  "latitude": "14.0583",
                  "longtitude": "108.2772",
                  "idQLC": 12483,
                  "idTimViec365": 240080,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "ULJo5iuGxJ",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": {
                      "scan": 0,
                      "account": {
                          "birthday": 999622800,
                          "gender": 1,
                          "married": 1,
                          "experience": 2,
                          "education": 0,
                          "_id": "64d0be0008c070461a7d7023"
                      },
                      "employee": {
                          "com_id": 3312,
                          "dep_id": 4221,
                          "start_working_time": 0,
                          "position_id": 4,
                          "team_id": 0,
                          "group_id": 0,
                          "time_quit_job": 0,
                          "ep_description": "Lập trình viên",
                          "ep_featured_recognition": "1",
                          "ep_status": "Active",
                          "ep_signature": 0,
                          "allow_update_face": 0,
                          "version_in_use": 0,
                          "_id": "64d0be0008c070461a7d7024"
                      },
                      "candidate": {
                          "use_type": 0,
                          "user_reset_time": 1688556121,
                          "use_view": 343,
                          "use_noti": 2,
                          "use_show": 1,
                          "use_show_cv": 0,
                          "use_active": 0,
                          "use_td": 0,
                          "use_check": 1,
                          "use_test": 0,
                          "point_time_active": 0,
                          "cv_title": "Lập trình viên php",
                          "cv_muctieu": "asd á dsa da",
                          "cv_city_id": [
                              1
                          ],
                          "cv_cate_id": [
                              30
                          ],
                          "cv_capbac_id": 3,
                          "cv_money_id": 1,
                          "cv_loaihinh_id": 1,
                          "cv_time": 1,
                          "cv_time_dl": 0,
                          "cv_kynang": "asdas d",
                          "um_type": 1,
                          "um_min_value": 0,
                          "um_max_value": null,
                          "um_unit": 1,
                          "cv_tc_name": "test",
                          "cv_tc_cv": "123",
                          "cv_tc_dc": "",
                          "cv_tc_phone": "0987654321",
                          "cv_tc_email": "12321@gmail.com",
                          "cv_tc_company": "123",
                          "cv_video": "",
                          "cv_video_type": 1,
                          "cv_video_active": 0,
                          "use_ip": "",
                          "time_send_vl": 1688972400,
                          "percents": 84,
                          "vip": 0,
                          "check_create_usc": 0,
                          "emp_id": 0,
                          "_id": "64d0be0008c070461a7d7025",
                          "profileDegree": [],
                          "profileNgoaiNgu": [],
                          "profileExperience": [],
                          "scan_audio": 0,
                          "audio": "",
                          "star3": 0,
                          "anhsao_badge": 0
                      },
                      "_id": "64d0be0008c070461a7d7022"
                  },
                  "inForCompany": null,
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "Nguyen Tuan Anh",
                      "doubleVerify": 0,
                      "active": 1,
                      "status": "0339170155",
                      "acceptMessStranger": 1,
                      "HistoryAccess": [
                          {
                              "IdDevice": "00331-10000-00001-AA654",
                              "IpAddress": "::ffff:210.245.75.51",
                              "NameDevice": "IPHONE-14PROMAX",
                              "Time": "2023-08-19T03:26:27.123Z",
                              "AccessPermision": true,
                              "_id": "64dd8ba3532167addbded2f5"
                          }
                      ]
                  },
                  "scan": 0,
                  "scanElacticAdmin": 1,
                  "scan_ai365": 2
              },
              "receiver": 1,
              "word": "ưdwdwdwd",
              "type": 0,
              "createAt": 1699352203.498
          },
          {
              "_id": "654a129b962b51d7806d10ba",
              "creator": {
                  "_id": 194081,
                  "email": "trantranghr.noithatanbinh@gmail.com",
                  "phoneTK": "",
                  "userName": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                  "alias": "cong-ty-co-phan-dau-tu-noi-that-an-binh",
                  "phone": "0374658298",
                  "emailContact": null,
                  "avatarUser": "avatar212244.png",
                  "type": 1,
                  "city": 1,
                  "district": 82,
                  "address": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                  "otp": "",
                  "authentic": 1,
                  "isOnline": 0,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1622193326,
                  "updatedAt": 1622193326,
                  "lastActivedAt": null,
                  "time_login": 1636103646,
                  "role": 0,
                  "latitude": "",
                  "longtitude": "",
                  "idQLC": 12483,
                  "idTimViec365": 212244,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "x7bPsv6lTr",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": null,
                  "inForCompany": {
                      "scan": 0,
                      "usc_kd": 9,
                      "usc_kd_first": 0,
                      "description": "\r\nCông ty nội thất AN BÌNH là một trong những công ty hàng đầu về thiết kế và thi công nội thất. Bằng tâm huyết, bằng kinh nghiệm, sự nhiệt tình và sáng tạo, đội ngũ nhân sự tự tin mang đến cho khách hàng những phong cách nội thất thẩm mỹ, nâng tầm giá trị cho căn nhà bạn. Đến với chúng tôi, bạn chắc chắn sẽ hài lòng về không gian sống của mình.\r\n\r\nGIÁ TRỊ CỐT LÕI\r\nVới AN BÌNH, chúng tôi hoạt động dựa trên tiêu chí giá trị cốt lõi sau đây:\r\n•\tTrung thực để phát triển bền vững.\r\n•\tĐề cao tinh thần hợp tác cùng phát triển.\r\n•\tHướng tới sự chuyên nghiệp hóa, tự động hóa.\r\n•\tĐặt lợi ích chung lên trên lợi ích cá nhân.\r\n•\tTôn trọng, tin cậy và đề cao chữ tín.\r\n\r\nAN BÌNH chú trọng đầu tư vào nhà xưởng, với trang thiết bị máy móc hiện đại cùng sự chuyên môn hóa trong từng bộ phận. Thêm vào đó đội ngũ quản lý và nhân viên chuyên nghiệp, giàu kinh nghiệm, có cái tâm và luôn đặt sự uy tín trong nghề nghiệp lên hàng đầu. Tất cả những điều đó đã làm nên một AN BÌNH chuyên nghiệp và có thể khiến khách hàng không thể không hài lòng khi đến.\r\n\r\nLĨNH VỰC HOẠT ĐỘNG:\r\nĐến với AN BÌNH, quý khách hàng có thể thấy được sự chuyên môn hóa trong từng lĩnh vực mà chúng tôi cung cấp đến cho khách hàng với:\r\n1.\tTư vấn giải pháp thiết kế nội thất, ngoại thất cho không gian sống của khách hàng.\r\n2.\tThiết kế không gian nội thất, ngoại thất cho khách hàng.\r\n3.\tThực hiện thi công từ A – Z cho mọi công trình của khách hàng.\r\nSự tin tưởng và ủng hộ của khách hàng trong suốt thời gian qua là nguồn động viên to lớn trên bước đường phát triển của AN BÌNH. Chúng tôi sẽ không ngừng hoàn thiện, phục vụ khách hàng tốt nhất để luôn xứng đáng với niềm tin ấy.\r\n",
                      "com_size": 0,
                      "timviec365": {
                          "usc_name": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                          "usc_name_add": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                          "usc_name_phone": "0374658298",
                          "usc_name_email": "trantranghr.noithatanbinh@gmail.com",
                          "usc_update_new": 1636103992,
                          "usc_canonical": "",
                          "usc_md5": "",
                          "usc_redirect": "",
                          "usc_type": 0,
                          "usc_size": 0,
                          "usc_website": "",
                          "usc_view_count": 0,
                          "usc_active": 0,
                          "usc_show": 1,
                          "usc_mail": 0,
                          "usc_stop_mail": 0,
                          "usc_utl": 0,
                          "usc_ssl": 0,
                          "usc_mst": "",
                          "usc_security": "",
                          "usc_ip": "183.81.105.94",
                          "usc_loc": 0,
                          "usc_mail_app": 0,
                          "usc_video": "",
                          "usc_video_type": 1,
                          "usc_video_active": 0,
                          "usc_block_account": 0,
                          "usc_stop_noti": 0,
                          "otp_time_exist": 0,
                          "usc_badge": 0,
                          "usc_star": 0,
                          "usc_vip": 0,
                          "usc_manager": "",
                          "usc_license": "",
                          "usc_active_license": 0,
                          "usc_map": "",
                          "usc_dgc": "1",
                          "usc_dgtv": "0",
                          "usc_dg_time": 0,
                          "usc_skype": "",
                          "usc_video_com": "",
                          "usc_lv": "nội thất",
                          "usc_test": 0,
                          "usc_zalo": null,
                          "usc_cc365": 0,
                          "usc_crm": 0,
                          "usc_images": null,
                          "usc_active_img": 0,
                          "usc_founded_time": 0,
                          "usc_branches": [],
                          "usc_xacthuc_email": 0,
                          "usc_note": ""
                      },
                      "cds": {
                          "com_role_id": 0,
                          "com_parent_id": null,
                          "type_timekeeping": "1,2,3,4,5,8,9",
                          "id_way_timekeeping": "1",
                          "com_qr_logo": null,
                          "enable_scan_qr": 0,
                          "com_vip": 0,
                          "com_ep_vip": 5,
                          "com_vip_time": 0,
                          "ep_crm": 0,
                          "ep_stt": 1
                      },
                      "_id": "65214b34c7b350eb7519ee09"
                  },
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "",
                      "doubleVerify": 0,
                      "active": 0,
                      "status": "",
                      "acceptMessStranger": 0,
                      "HistoryAccess": []
                  },
                  "scan": 0,
                  "emotion_active": false,
                  "scanElacticAdmin": 1
              },
              "receiver": 1,
              "word": "ưdwdwdwd",
              "type": 0,
              "createAt": 1699352203.498
          },
          {
              "_id": "654b122bc0edfca7f5e42118",
              "creator": {
                  "_id": 17496,
                  "email": "tuananhhust05@gmail.com",
                  "phoneTK": "",
                  "userName": "Nguyễn Tuấn Anh",
                  "alias": "adfultre",
                  "phone": "0339170155",
                  "emailContact": null,
                  "avatarUser": "app1691748972_360 3.jpg",
                  "type": 2,
                  "city": 1,
                  "district": 82,
                  "address": "Đức Lý, Lý Nhân, Hà Nam",
                  "otp": "0",
                  "authentic": 1,
                  "isOnline": 1,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1681531709,
                  "updatedAt": 1699424378,
                  "lastActivedAt": "2023-11-08T06:19:38.415Z",
                  "time_login": 1690970480,
                  "role": 0,
                  "latitude": "14.0583",
                  "longtitude": "108.2772",
                  "idQLC": 12483,
                  "idTimViec365": 240080,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "ULJo5iuGxJ",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": {
                      "scan": 0,
                      "account": {
                          "birthday": 999622800,
                          "gender": 1,
                          "married": 1,
                          "experience": 2,
                          "education": 0,
                          "_id": "64d0be0008c070461a7d7023"
                      },
                      "employee": {
                          "com_id": 3312,
                          "dep_id": 4221,
                          "start_working_time": 0,
                          "position_id": 4,
                          "team_id": 0,
                          "group_id": 0,
                          "time_quit_job": 0,
                          "ep_description": "Lập trình viên",
                          "ep_featured_recognition": "1",
                          "ep_status": "Active",
                          "ep_signature": 0,
                          "allow_update_face": 0,
                          "version_in_use": 0,
                          "_id": "64d0be0008c070461a7d7024"
                      },
                      "candidate": {
                          "use_type": 0,
                          "user_reset_time": 1688556121,
                          "use_view": 343,
                          "use_noti": 2,
                          "use_show": 1,
                          "use_show_cv": 0,
                          "use_active": 0,
                          "use_td": 0,
                          "use_check": 1,
                          "use_test": 0,
                          "point_time_active": 0,
                          "cv_title": "Lập trình viên php",
                          "cv_muctieu": "asd á dsa da",
                          "cv_city_id": [
                              1
                          ],
                          "cv_cate_id": [
                              30
                          ],
                          "cv_capbac_id": 3,
                          "cv_money_id": 1,
                          "cv_loaihinh_id": 1,
                          "cv_time": 1,
                          "cv_time_dl": 0,
                          "cv_kynang": "asdas d",
                          "um_type": 1,
                          "um_min_value": 0,
                          "um_max_value": null,
                          "um_unit": 1,
                          "cv_tc_name": "test",
                          "cv_tc_cv": "123",
                          "cv_tc_dc": "",
                          "cv_tc_phone": "0987654321",
                          "cv_tc_email": "12321@gmail.com",
                          "cv_tc_company": "123",
                          "cv_video": "",
                          "cv_video_type": 1,
                          "cv_video_active": 0,
                          "use_ip": "",
                          "time_send_vl": 1688972400,
                          "percents": 84,
                          "vip": 0,
                          "check_create_usc": 0,
                          "emp_id": 0,
                          "_id": "64d0be0008c070461a7d7025",
                          "profileDegree": [],
                          "profileNgoaiNgu": [],
                          "profileExperience": [],
                          "scan_audio": 0,
                          "audio": "",
                          "star3": 0,
                          "anhsao_badge": 0
                      },
                      "_id": "64d0be0008c070461a7d7022"
                  },
                  "inForCompany": null,
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "Nguyen Tuan Anh",
                      "doubleVerify": 0,
                      "active": 1,
                      "status": "0339170155",
                      "acceptMessStranger": 1,
                      "HistoryAccess": [
                          {
                              "IdDevice": "00331-10000-00001-AA654",
                              "IpAddress": "::ffff:210.245.75.51",
                              "NameDevice": "IPHONE-14PROMAX",
                              "Time": "2023-08-19T03:26:27.123Z",
                              "AccessPermision": true,
                              "_id": "64dd8ba3532167addbded2f5"
                          }
                      ]
                  },
                  "scan": 0,
                  "scanElacticAdmin": 1,
                  "scan_ai365": 2
              },
              "receiver": 1,
              "word": "ưdwdwdwd",
              "type": 0,
              "createAt": 1699376686.275
          },
          {
              "_id": "654b122bc0edfca7f5e42118",
              "creator": {
                  "_id": 194081,
                  "email": "trantranghr.noithatanbinh@gmail.com",
                  "phoneTK": "",
                  "userName": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                  "alias": "cong-ty-co-phan-dau-tu-noi-that-an-binh",
                  "phone": "0374658298",
                  "emailContact": null,
                  "avatarUser": "avatar212244.png",
                  "type": 1,
                  "city": 1,
                  "district": 82,
                  "address": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                  "otp": "",
                  "authentic": 1,
                  "isOnline": 0,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1622193326,
                  "updatedAt": 1622193326,
                  "lastActivedAt": null,
                  "time_login": 1636103646,
                  "role": 0,
                  "latitude": "",
                  "longtitude": "",
                  "idQLC": 12483,
                  "idTimViec365": 212244,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "x7bPsv6lTr",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": null,
                  "inForCompany": {
                      "scan": 0,
                      "usc_kd": 9,
                      "usc_kd_first": 0,
                      "description": "\r\nCông ty nội thất AN BÌNH là một trong những công ty hàng đầu về thiết kế và thi công nội thất. Bằng tâm huyết, bằng kinh nghiệm, sự nhiệt tình và sáng tạo, đội ngũ nhân sự tự tin mang đến cho khách hàng những phong cách nội thất thẩm mỹ, nâng tầm giá trị cho căn nhà bạn. Đến với chúng tôi, bạn chắc chắn sẽ hài lòng về không gian sống của mình.\r\n\r\nGIÁ TRỊ CỐT LÕI\r\nVới AN BÌNH, chúng tôi hoạt động dựa trên tiêu chí giá trị cốt lõi sau đây:\r\n•\tTrung thực để phát triển bền vững.\r\n•\tĐề cao tinh thần hợp tác cùng phát triển.\r\n•\tHướng tới sự chuyên nghiệp hóa, tự động hóa.\r\n•\tĐặt lợi ích chung lên trên lợi ích cá nhân.\r\n•\tTôn trọng, tin cậy và đề cao chữ tín.\r\n\r\nAN BÌNH chú trọng đầu tư vào nhà xưởng, với trang thiết bị máy móc hiện đại cùng sự chuyên môn hóa trong từng bộ phận. Thêm vào đó đội ngũ quản lý và nhân viên chuyên nghiệp, giàu kinh nghiệm, có cái tâm và luôn đặt sự uy tín trong nghề nghiệp lên hàng đầu. Tất cả những điều đó đã làm nên một AN BÌNH chuyên nghiệp và có thể khiến khách hàng không thể không hài lòng khi đến.\r\n\r\nLĨNH VỰC HOẠT ĐỘNG:\r\nĐến với AN BÌNH, quý khách hàng có thể thấy được sự chuyên môn hóa trong từng lĩnh vực mà chúng tôi cung cấp đến cho khách hàng với:\r\n1.\tTư vấn giải pháp thiết kế nội thất, ngoại thất cho không gian sống của khách hàng.\r\n2.\tThiết kế không gian nội thất, ngoại thất cho khách hàng.\r\n3.\tThực hiện thi công từ A – Z cho mọi công trình của khách hàng.\r\nSự tin tưởng và ủng hộ của khách hàng trong suốt thời gian qua là nguồn động viên to lớn trên bước đường phát triển của AN BÌNH. Chúng tôi sẽ không ngừng hoàn thiện, phục vụ khách hàng tốt nhất để luôn xứng đáng với niềm tin ấy.\r\n",
                      "com_size": 0,
                      "timviec365": {
                          "usc_name": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                          "usc_name_add": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                          "usc_name_phone": "0374658298",
                          "usc_name_email": "trantranghr.noithatanbinh@gmail.com",
                          "usc_update_new": 1636103992,
                          "usc_canonical": "",
                          "usc_md5": "",
                          "usc_redirect": "",
                          "usc_type": 0,
                          "usc_size": 0,
                          "usc_website": "",
                          "usc_view_count": 0,
                          "usc_active": 0,
                          "usc_show": 1,
                          "usc_mail": 0,
                          "usc_stop_mail": 0,
                          "usc_utl": 0,
                          "usc_ssl": 0,
                          "usc_mst": "",
                          "usc_security": "",
                          "usc_ip": "183.81.105.94",
                          "usc_loc": 0,
                          "usc_mail_app": 0,
                          "usc_video": "",
                          "usc_video_type": 1,
                          "usc_video_active": 0,
                          "usc_block_account": 0,
                          "usc_stop_noti": 0,
                          "otp_time_exist": 0,
                          "usc_badge": 0,
                          "usc_star": 0,
                          "usc_vip": 0,
                          "usc_manager": "",
                          "usc_license": "",
                          "usc_active_license": 0,
                          "usc_map": "",
                          "usc_dgc": "1",
                          "usc_dgtv": "0",
                          "usc_dg_time": 0,
                          "usc_skype": "",
                          "usc_video_com": "",
                          "usc_lv": "nội thất",
                          "usc_test": 0,
                          "usc_zalo": null,
                          "usc_cc365": 0,
                          "usc_crm": 0,
                          "usc_images": null,
                          "usc_active_img": 0,
                          "usc_founded_time": 0,
                          "usc_branches": [],
                          "usc_xacthuc_email": 0,
                          "usc_note": ""
                      },
                      "cds": {
                          "com_role_id": 0,
                          "com_parent_id": null,
                          "type_timekeeping": "1,2,3,4,5,8,9",
                          "id_way_timekeeping": "1",
                          "com_qr_logo": null,
                          "enable_scan_qr": 0,
                          "com_vip": 0,
                          "com_ep_vip": 5,
                          "com_vip_time": 0,
                          "ep_crm": 0,
                          "ep_stt": 1
                      },
                      "_id": "65214b34c7b350eb7519ee09"
                  },
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "",
                      "doubleVerify": 0,
                      "active": 0,
                      "status": "",
                      "acceptMessStranger": 0,
                      "HistoryAccess": []
                  },
                  "scan": 0,
                  "emotion_active": false,
                  "scanElacticAdmin": 1
              },
              "receiver": 1,
              "word": "ưdwdwdwd",
              "type": 0,
              "createAt": 1699376686.275
          },
          {
              "_id": "654b2de2c4074b47c8bb69dd",
              "creator": {
                  "_id": 17496,
                  "email": "tuananhhust05@gmail.com",
                  "phoneTK": "",
                  "userName": "Nguyễn Tuấn Anh",
                  "alias": "adfultre",
                  "phone": "0339170155",
                  "emailContact": null,
                  "avatarUser": "app1691748972_360 3.jpg",
                  "type": 2,
                  "city": 1,
                  "district": 82,
                  "address": "Đức Lý, Lý Nhân, Hà Nam",
                  "otp": "0",
                  "authentic": 1,
                  "isOnline": 1,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1681531709,
                  "updatedAt": 1699424378,
                  "lastActivedAt": "2023-11-08T06:19:38.415Z",
                  "time_login": 1690970480,
                  "role": 0,
                  "latitude": "14.0583",
                  "longtitude": "108.2772",
                  "idQLC": 12483,
                  "idTimViec365": 240080,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "ULJo5iuGxJ",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": {
                      "scan": 0,
                      "account": {
                          "birthday": 999622800,
                          "gender": 1,
                          "married": 1,
                          "experience": 2,
                          "education": 0,
                          "_id": "64d0be0008c070461a7d7023"
                      },
                      "employee": {
                          "com_id": 3312,
                          "dep_id": 4221,
                          "start_working_time": 0,
                          "position_id": 4,
                          "team_id": 0,
                          "group_id": 0,
                          "time_quit_job": 0,
                          "ep_description": "Lập trình viên",
                          "ep_featured_recognition": "1",
                          "ep_status": "Active",
                          "ep_signature": 0,
                          "allow_update_face": 0,
                          "version_in_use": 0,
                          "_id": "64d0be0008c070461a7d7024"
                      },
                      "candidate": {
                          "use_type": 0,
                          "user_reset_time": 1688556121,
                          "use_view": 343,
                          "use_noti": 2,
                          "use_show": 1,
                          "use_show_cv": 0,
                          "use_active": 0,
                          "use_td": 0,
                          "use_check": 1,
                          "use_test": 0,
                          "point_time_active": 0,
                          "cv_title": "Lập trình viên php",
                          "cv_muctieu": "asd á dsa da",
                          "cv_city_id": [
                              1
                          ],
                          "cv_cate_id": [
                              30
                          ],
                          "cv_capbac_id": 3,
                          "cv_money_id": 1,
                          "cv_loaihinh_id": 1,
                          "cv_time": 1,
                          "cv_time_dl": 0,
                          "cv_kynang": "asdas d",
                          "um_type": 1,
                          "um_min_value": 0,
                          "um_max_value": null,
                          "um_unit": 1,
                          "cv_tc_name": "test",
                          "cv_tc_cv": "123",
                          "cv_tc_dc": "",
                          "cv_tc_phone": "0987654321",
                          "cv_tc_email": "12321@gmail.com",
                          "cv_tc_company": "123",
                          "cv_video": "",
                          "cv_video_type": 1,
                          "cv_video_active": 0,
                          "use_ip": "",
                          "time_send_vl": 1688972400,
                          "percents": 84,
                          "vip": 0,
                          "check_create_usc": 0,
                          "emp_id": 0,
                          "_id": "64d0be0008c070461a7d7025",
                          "profileDegree": [],
                          "profileNgoaiNgu": [],
                          "profileExperience": [],
                          "scan_audio": 0,
                          "audio": "",
                          "star3": 0,
                          "anhsao_badge": 0
                      },
                      "_id": "64d0be0008c070461a7d7022"
                  },
                  "inForCompany": null,
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "Nguyen Tuan Anh",
                      "doubleVerify": 0,
                      "active": 1,
                      "status": "0339170155",
                      "acceptMessStranger": 1,
                      "HistoryAccess": [
                          {
                              "IdDevice": "00331-10000-00001-AA654",
                              "IpAddress": "::ffff:210.245.75.51",
                              "NameDevice": "IPHONE-14PROMAX",
                              "Time": "2023-08-19T03:26:27.123Z",
                              "AccessPermision": true,
                              "_id": "64dd8ba3532167addbded2f5"
                          }
                      ]
                  },
                  "scan": 0,
                  "scanElacticAdmin": 1,
                  "scan_ai365": 2
              },
              "receiver": 1,
              "word": "test1",
              "type": 0,
              "createAt": 1699420295.878
          },
          {
              "_id": "654b2de2c4074b47c8bb69dd",
              "creator": {
                  "_id": 194081,
                  "email": "trantranghr.noithatanbinh@gmail.com",
                  "phoneTK": "",
                  "userName": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                  "alias": "cong-ty-co-phan-dau-tu-noi-that-an-binh",
                  "phone": "0374658298",
                  "emailContact": null,
                  "avatarUser": "avatar212244.png",
                  "type": 1,
                  "city": 1,
                  "district": 82,
                  "address": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                  "otp": "",
                  "authentic": 1,
                  "isOnline": 0,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1622193326,
                  "updatedAt": 1622193326,
                  "lastActivedAt": null,
                  "time_login": 1636103646,
                  "role": 0,
                  "latitude": "",
                  "longtitude": "",
                  "idQLC": 12483,
                  "idTimViec365": 212244,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "x7bPsv6lTr",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": null,
                  "inForCompany": {
                      "scan": 0,
                      "usc_kd": 9,
                      "usc_kd_first": 0,
                      "description": "\r\nCông ty nội thất AN BÌNH là một trong những công ty hàng đầu về thiết kế và thi công nội thất. Bằng tâm huyết, bằng kinh nghiệm, sự nhiệt tình và sáng tạo, đội ngũ nhân sự tự tin mang đến cho khách hàng những phong cách nội thất thẩm mỹ, nâng tầm giá trị cho căn nhà bạn. Đến với chúng tôi, bạn chắc chắn sẽ hài lòng về không gian sống của mình.\r\n\r\nGIÁ TRỊ CỐT LÕI\r\nVới AN BÌNH, chúng tôi hoạt động dựa trên tiêu chí giá trị cốt lõi sau đây:\r\n•\tTrung thực để phát triển bền vững.\r\n•\tĐề cao tinh thần hợp tác cùng phát triển.\r\n•\tHướng tới sự chuyên nghiệp hóa, tự động hóa.\r\n•\tĐặt lợi ích chung lên trên lợi ích cá nhân.\r\n•\tTôn trọng, tin cậy và đề cao chữ tín.\r\n\r\nAN BÌNH chú trọng đầu tư vào nhà xưởng, với trang thiết bị máy móc hiện đại cùng sự chuyên môn hóa trong từng bộ phận. Thêm vào đó đội ngũ quản lý và nhân viên chuyên nghiệp, giàu kinh nghiệm, có cái tâm và luôn đặt sự uy tín trong nghề nghiệp lên hàng đầu. Tất cả những điều đó đã làm nên một AN BÌNH chuyên nghiệp và có thể khiến khách hàng không thể không hài lòng khi đến.\r\n\r\nLĨNH VỰC HOẠT ĐỘNG:\r\nĐến với AN BÌNH, quý khách hàng có thể thấy được sự chuyên môn hóa trong từng lĩnh vực mà chúng tôi cung cấp đến cho khách hàng với:\r\n1.\tTư vấn giải pháp thiết kế nội thất, ngoại thất cho không gian sống của khách hàng.\r\n2.\tThiết kế không gian nội thất, ngoại thất cho khách hàng.\r\n3.\tThực hiện thi công từ A – Z cho mọi công trình của khách hàng.\r\nSự tin tưởng và ủng hộ của khách hàng trong suốt thời gian qua là nguồn động viên to lớn trên bước đường phát triển của AN BÌNH. Chúng tôi sẽ không ngừng hoàn thiện, phục vụ khách hàng tốt nhất để luôn xứng đáng với niềm tin ấy.\r\n",
                      "com_size": 0,
                      "timviec365": {
                          "usc_name": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                          "usc_name_add": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                          "usc_name_phone": "0374658298",
                          "usc_name_email": "trantranghr.noithatanbinh@gmail.com",
                          "usc_update_new": 1636103992,
                          "usc_canonical": "",
                          "usc_md5": "",
                          "usc_redirect": "",
                          "usc_type": 0,
                          "usc_size": 0,
                          "usc_website": "",
                          "usc_view_count": 0,
                          "usc_active": 0,
                          "usc_show": 1,
                          "usc_mail": 0,
                          "usc_stop_mail": 0,
                          "usc_utl": 0,
                          "usc_ssl": 0,
                          "usc_mst": "",
                          "usc_security": "",
                          "usc_ip": "183.81.105.94",
                          "usc_loc": 0,
                          "usc_mail_app": 0,
                          "usc_video": "",
                          "usc_video_type": 1,
                          "usc_video_active": 0,
                          "usc_block_account": 0,
                          "usc_stop_noti": 0,
                          "otp_time_exist": 0,
                          "usc_badge": 0,
                          "usc_star": 0,
                          "usc_vip": 0,
                          "usc_manager": "",
                          "usc_license": "",
                          "usc_active_license": 0,
                          "usc_map": "",
                          "usc_dgc": "1",
                          "usc_dgtv": "0",
                          "usc_dg_time": 0,
                          "usc_skype": "",
                          "usc_video_com": "",
                          "usc_lv": "nội thất",
                          "usc_test": 0,
                          "usc_zalo": null,
                          "usc_cc365": 0,
                          "usc_crm": 0,
                          "usc_images": null,
                          "usc_active_img": 0,
                          "usc_founded_time": 0,
                          "usc_branches": [],
                          "usc_xacthuc_email": 0,
                          "usc_note": ""
                      },
                      "cds": {
                          "com_role_id": 0,
                          "com_parent_id": null,
                          "type_timekeeping": "1,2,3,4,5,8,9",
                          "id_way_timekeeping": "1",
                          "com_qr_logo": null,
                          "enable_scan_qr": 0,
                          "com_vip": 0,
                          "com_ep_vip": 5,
                          "com_vip_time": 0,
                          "ep_crm": 0,
                          "ep_stt": 1
                      },
                      "_id": "65214b34c7b350eb7519ee09"
                  },
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "",
                      "doubleVerify": 0,
                      "active": 0,
                      "status": "",
                      "acceptMessStranger": 0,
                      "HistoryAccess": []
                  },
                  "scan": 0,
                  "emotion_active": false,
                  "scanElacticAdmin": 1
              },
              "receiver": 1,
              "word": "test1",
              "type": 0,
              "createAt": 1699420295.878
          },
          {
              "_id": "654b2e4dc4074b47c8bb69e2",
              "creator": {
                  "_id": 17496,
                  "email": "tuananhhust05@gmail.com",
                  "phoneTK": "",
                  "userName": "Nguyễn Tuấn Anh",
                  "alias": "adfultre",
                  "phone": "0339170155",
                  "emailContact": null,
                  "avatarUser": "app1691748972_360 3.jpg",
                  "type": 2,
                  "city": 1,
                  "district": 82,
                  "address": "Đức Lý, Lý Nhân, Hà Nam",
                  "otp": "0",
                  "authentic": 1,
                  "isOnline": 1,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1681531709,
                  "updatedAt": 1699424378,
                  "lastActivedAt": "2023-11-08T06:19:38.415Z",
                  "time_login": 1690970480,
                  "role": 0,
                  "latitude": "14.0583",
                  "longtitude": "108.2772",
                  "idQLC": 12483,
                  "idTimViec365": 240080,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "ULJo5iuGxJ",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": {
                      "scan": 0,
                      "account": {
                          "birthday": 999622800,
                          "gender": 1,
                          "married": 1,
                          "experience": 2,
                          "education": 0,
                          "_id": "64d0be0008c070461a7d7023"
                      },
                      "employee": {
                          "com_id": 3312,
                          "dep_id": 4221,
                          "start_working_time": 0,
                          "position_id": 4,
                          "team_id": 0,
                          "group_id": 0,
                          "time_quit_job": 0,
                          "ep_description": "Lập trình viên",
                          "ep_featured_recognition": "1",
                          "ep_status": "Active",
                          "ep_signature": 0,
                          "allow_update_face": 0,
                          "version_in_use": 0,
                          "_id": "64d0be0008c070461a7d7024"
                      },
                      "candidate": {
                          "use_type": 0,
                          "user_reset_time": 1688556121,
                          "use_view": 343,
                          "use_noti": 2,
                          "use_show": 1,
                          "use_show_cv": 0,
                          "use_active": 0,
                          "use_td": 0,
                          "use_check": 1,
                          "use_test": 0,
                          "point_time_active": 0,
                          "cv_title": "Lập trình viên php",
                          "cv_muctieu": "asd á dsa da",
                          "cv_city_id": [
                              1
                          ],
                          "cv_cate_id": [
                              30
                          ],
                          "cv_capbac_id": 3,
                          "cv_money_id": 1,
                          "cv_loaihinh_id": 1,
                          "cv_time": 1,
                          "cv_time_dl": 0,
                          "cv_kynang": "asdas d",
                          "um_type": 1,
                          "um_min_value": 0,
                          "um_max_value": null,
                          "um_unit": 1,
                          "cv_tc_name": "test",
                          "cv_tc_cv": "123",
                          "cv_tc_dc": "",
                          "cv_tc_phone": "0987654321",
                          "cv_tc_email": "12321@gmail.com",
                          "cv_tc_company": "123",
                          "cv_video": "",
                          "cv_video_type": 1,
                          "cv_video_active": 0,
                          "use_ip": "",
                          "time_send_vl": 1688972400,
                          "percents": 84,
                          "vip": 0,
                          "check_create_usc": 0,
                          "emp_id": 0,
                          "_id": "64d0be0008c070461a7d7025",
                          "profileDegree": [],
                          "profileNgoaiNgu": [],
                          "profileExperience": [],
                          "scan_audio": 0,
                          "audio": "",
                          "star3": 0,
                          "anhsao_badge": 0
                      },
                      "_id": "64d0be0008c070461a7d7022"
                  },
                  "inForCompany": null,
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "Nguyen Tuan Anh",
                      "doubleVerify": 0,
                      "active": 1,
                      "status": "0339170155",
                      "acceptMessStranger": 1,
                      "HistoryAccess": [
                          {
                              "IdDevice": "00331-10000-00001-AA654",
                              "IpAddress": "::ffff:210.245.75.51",
                              "NameDevice": "IPHONE-14PROMAX",
                              "Time": "2023-08-19T03:26:27.123Z",
                              "AccessPermision": true,
                              "_id": "64dd8ba3532167addbded2f5"
                          }
                      ]
                  },
                  "scan": 0,
                  "scanElacticAdmin": 1,
                  "scan_ai365": 2
              },
              "receiver": 1,
              "word": "test2",
              "type": 0,
              "createAt": 1699420295.878
          },
          {
              "_id": "654b2e4dc4074b47c8bb69e2",
              "creator": {
                  "_id": 194081,
                  "email": "trantranghr.noithatanbinh@gmail.com",
                  "phoneTK": "",
                  "userName": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                  "alias": "cong-ty-co-phan-dau-tu-noi-that-an-binh",
                  "phone": "0374658298",
                  "emailContact": null,
                  "avatarUser": "avatar212244.png",
                  "type": 1,
                  "city": 1,
                  "district": 82,
                  "address": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                  "otp": "",
                  "authentic": 1,
                  "isOnline": 0,
                  "fromWeb": "timviec365",
                  "fromDevice": 1,
                  "createdAt": 1622193326,
                  "updatedAt": 1622193326,
                  "lastActivedAt": null,
                  "time_login": 1636103646,
                  "role": 0,
                  "latitude": "",
                  "longtitude": "",
                  "idQLC": 12483,
                  "idTimViec365": 212244,
                  "idRaoNhanh365": 0,
                  "chat365_secret": "x7bPsv6lTr",
                  "chat365_id": 0,
                  "scan_base365": 0,
                  "check_chat": 0,
                  "sharePermissionId": [],
                  "inForPerson": null,
                  "inForCompany": {
                      "scan": 0,
                      "usc_kd": 9,
                      "usc_kd_first": 0,
                      "description": "\r\nCông ty nội thất AN BÌNH là một trong những công ty hàng đầu về thiết kế và thi công nội thất. Bằng tâm huyết, bằng kinh nghiệm, sự nhiệt tình và sáng tạo, đội ngũ nhân sự tự tin mang đến cho khách hàng những phong cách nội thất thẩm mỹ, nâng tầm giá trị cho căn nhà bạn. Đến với chúng tôi, bạn chắc chắn sẽ hài lòng về không gian sống của mình.\r\n\r\nGIÁ TRỊ CỐT LÕI\r\nVới AN BÌNH, chúng tôi hoạt động dựa trên tiêu chí giá trị cốt lõi sau đây:\r\n•\tTrung thực để phát triển bền vững.\r\n•\tĐề cao tinh thần hợp tác cùng phát triển.\r\n•\tHướng tới sự chuyên nghiệp hóa, tự động hóa.\r\n•\tĐặt lợi ích chung lên trên lợi ích cá nhân.\r\n•\tTôn trọng, tin cậy và đề cao chữ tín.\r\n\r\nAN BÌNH chú trọng đầu tư vào nhà xưởng, với trang thiết bị máy móc hiện đại cùng sự chuyên môn hóa trong từng bộ phận. Thêm vào đó đội ngũ quản lý và nhân viên chuyên nghiệp, giàu kinh nghiệm, có cái tâm và luôn đặt sự uy tín trong nghề nghiệp lên hàng đầu. Tất cả những điều đó đã làm nên một AN BÌNH chuyên nghiệp và có thể khiến khách hàng không thể không hài lòng khi đến.\r\n\r\nLĨNH VỰC HOẠT ĐỘNG:\r\nĐến với AN BÌNH, quý khách hàng có thể thấy được sự chuyên môn hóa trong từng lĩnh vực mà chúng tôi cung cấp đến cho khách hàng với:\r\n1.\tTư vấn giải pháp thiết kế nội thất, ngoại thất cho không gian sống của khách hàng.\r\n2.\tThiết kế không gian nội thất, ngoại thất cho khách hàng.\r\n3.\tThực hiện thi công từ A – Z cho mọi công trình của khách hàng.\r\nSự tin tưởng và ủng hộ của khách hàng trong suốt thời gian qua là nguồn động viên to lớn trên bước đường phát triển của AN BÌNH. Chúng tôi sẽ không ngừng hoàn thiện, phục vụ khách hàng tốt nhất để luôn xứng đáng với niềm tin ấy.\r\n",
                      "com_size": 0,
                      "timviec365": {
                          "usc_name": "Công Ty Cổ Phần Đầu Tư Nội Thất An Bình",
                          "usc_name_add": "Phòng 12A07, Tòa A, Hồ Gươm Plaza, 102 Trần Phú",
                          "usc_name_phone": "0374658298",
                          "usc_name_email": "trantranghr.noithatanbinh@gmail.com",
                          "usc_update_new": 1636103992,
                          "usc_canonical": "",
                          "usc_md5": "",
                          "usc_redirect": "",
                          "usc_type": 0,
                          "usc_size": 0,
                          "usc_website": "",
                          "usc_view_count": 0,
                          "usc_active": 0,
                          "usc_show": 1,
                          "usc_mail": 0,
                          "usc_stop_mail": 0,
                          "usc_utl": 0,
                          "usc_ssl": 0,
                          "usc_mst": "",
                          "usc_security": "",
                          "usc_ip": "183.81.105.94",
                          "usc_loc": 0,
                          "usc_mail_app": 0,
                          "usc_video": "",
                          "usc_video_type": 1,
                          "usc_video_active": 0,
                          "usc_block_account": 0,
                          "usc_stop_noti": 0,
                          "otp_time_exist": 0,
                          "usc_badge": 0,
                          "usc_star": 0,
                          "usc_vip": 0,
                          "usc_manager": "",
                          "usc_license": "",
                          "usc_active_license": 0,
                          "usc_map": "",
                          "usc_dgc": "1",
                          "usc_dgtv": "0",
                          "usc_dg_time": 0,
                          "usc_skype": "",
                          "usc_video_com": "",
                          "usc_lv": "nội thất",
                          "usc_test": 0,
                          "usc_zalo": null,
                          "usc_cc365": 0,
                          "usc_crm": 0,
                          "usc_images": null,
                          "usc_active_img": 0,
                          "usc_founded_time": 0,
                          "usc_branches": [],
                          "usc_xacthuc_email": 0,
                          "usc_note": ""
                      },
                      "cds": {
                          "com_role_id": 0,
                          "com_parent_id": null,
                          "type_timekeeping": "1,2,3,4,5,8,9",
                          "id_way_timekeeping": "1",
                          "com_qr_logo": null,
                          "enable_scan_qr": 0,
                          "com_vip": 0,
                          "com_ep_vip": 5,
                          "com_vip_time": 0,
                          "ep_crm": 0,
                          "ep_stt": 1
                      },
                      "_id": "65214b34c7b350eb7519ee09"
                  },
                  "inforRN365": null,
                  "configChat": {
                      "notificationAcceptOffer": 1,
                      "notificationAllocationRecall": 1,
                      "notificationChangeSalary": 1,
                      "notificationCommentFromRaoNhanh": 1,
                      "notificationCommentFromTimViec": 1,
                      "notificationDecilineOffer": 1,
                      "notificationMissMessage": 1,
                      "notificationNTDExpiredPin": 1,
                      "notificationNTDExpiredRecruit": 1,
                      "notificationNTDPoint": 1,
                      "notificationSendCandidate": 1,
                      "notificationTag": 1,
                      "removeSugges": [],
                      "userNameNoVn": "",
                      "doubleVerify": 0,
                      "active": 0,
                      "status": "",
                      "acceptMessStranger": 0,
                      "HistoryAccess": []
                  },
                  "scan": 0,
                  "emotion_active": false,
                  "scanElacticAdmin": 1
              },
              "receiver": 1,
              "word": "test2",
              "type": 0,
              "createAt": 1699420295.878
          }
      ]
  }
}